import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import MainBody from '../components/MainBody/MainBody'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Gerard's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script defer src="https://cdn.jsdelivr.net/npm/tsparticles-preset-stars@2/tsparticles.preset.stars.bundle.min.js"></script>
      </Head>
      <MainBody/>
    </div>
  )
}
