import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import MainBody from '../components/MainBody/MainBody'
import Experience from '../components/Experience/Experience'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Gerard's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainBody/>
      <Experience/>
    </div>
  )
}
